//Productos

const Productos = [
    {
        id: 1,
        nombre: "producto1",
        img: "",
        precio: 80000,
        descripcion: "",
    },
    {
        id: 2,
        nombre: "producto2",
        img: "",
        precio: 80000,
        descripcion: "",
    },
    {
        id: 3,
        nombre: "producto3",
        img: "",
        precio: 80000,
        descripcion: "",
    },
    {
        id: 4,
        nombre: "producto4",
        img: "",
        precio: 80000,
        descripcion: "",
    },
    {
        id: 5,
        nombre: "producto5",
        img: "",
        precio: 90000,
        descripcion: "",
    },
    {
        id: 6,
        nombre: "producto6",
        img: "",
        precio: 90000,
        descripcion: "",
    },
    {
        id: 7,
        nombre: "producto7",
        img: "",
        precio: 90000,
        descripcion: "",
    },
    {
        id: 8,
        nombre: "producto8",
        img: "",
        precio: 90000,
        descripcion: "",
    },
    {
        id: 9,
        nombre: "producto9",
        img: "",
        precio: 40000,
        descripcion: "",
    },
    {
        id: 10,
        nombre: "producto10",
        img: "",
        precio: 40000,
        descripcion: "",
    },
    {
        id: 11,
        nombre: "producto11",
        img: "",
        precio: 40000,
        descripcion: "",
    },
    {
        id: 12,
        nombre: "producto12",
        img: "",
        precio: 40000,
        descripcion: "",
    },
]